# Generated by Django 2.2.3 on 2020-11-06 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0011_pokemon_previous_evolution'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pokemon',
            old_name='previous_evolution',
            new_name='parent',
        ),
    ]
