# Generated by Django 2.2.3 on 2020-11-06 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0015_auto_20201106_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='image',
            field=models.ImageField(default='https://vignette.wikia.nocookie.net/pokemon/images/6/6e/%21.png/\n                       revision/latest/fixed-aspect-ratio-down/width/240/height/\n                       240?cb=20130525215832&fill=transparent', upload_to='pokemons_img', verbose_name='Картинка'),
        ),
    ]
