# Generated by Django 2.2.3 on 2020-11-06 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0019_auto_20201106_1743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='image',
            field=models.ImageField(default='sd', upload_to='pokemons_img', verbose_name='Картинка'),
            preserve_default=False,
        ),
    ]
