# Generated by Django 2.2.3 on 2020-11-07 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0021_auto_20201107_1001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemonelementtype',
            name='title',
            field=models.CharField(max_length=20),
        ),
    ]
