# Generated by Django 2.2.3 on 2020-11-09 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0022_auto_20201107_1005'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemonelementtype',
            name='image',
            field=models.ImageField(default='default', upload_to='pokemons_elemnt_img', verbose_name='Стихия картинка'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pokemonelementtype',
            name='title',
            field=models.CharField(max_length=20, verbose_name='Название'),
        ),
    ]
